### ISSUE TITLE
How are the files under "CSU-RM-Sentry-main\src\rm_navigation\map" generated?

### ISSUE THREAD

**Issue by ssevenmoons** [baiyeweiguang/CSU-RM-Sentry#1]
The "ros2 launch pointcloud_to_laserscan pointcloud_to_laserscan_launch. py" in mapping. sh seems to be only related to navigation and not related to fastlio. Is it necessary to run TUP2023 Sentry Nav code to obtain the map file of "CSU-RM-Sentry-main\src\rm_navigation\map\" after obtaining the pcd file from Fast-lio?

**Comment by baiyeweiguang** [comment]
When FAST_LIO is running and the parameter `pcd_save_en : true`  is set to true, you can get the PCD file by **calling the service**  `/map_save`. 

For 2D occupancy grid maps, save the map like a regular Nav2 program, that is to say, you can save the pgm file with **runing map_saver_cli** `ros2 run nav2_map_server map_saver_cli -f your_map_name`. 

There is no need to run additional code, but of course, you can write a simple save file script if you find this too much trouble.
